version: "3"
services:
  apisix:
    image: apache/apisix:3.0.0-debian
    environment:
      ETCD_HOST: "etcd"
    volumes:
      - ./apisix/config.yml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix/routes.yml:/usr/local/apisix/conf/apisix.yaml:ro
    ports:
      - "9080:9080"
    restart: always
    depends_on:
      - etcd
  etcd:
    image: bitnami/etcd:3.5.6
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2397"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2397"
  content:
    image: busybox:1.34
    command: ["/bin/busybox", "httpd", "-h", "/www", "-f", "-p", "8080"]
    volumes:
      - ./static:/www
    ports:
      - "8080:8080"
